name: Update Manifest on Develop Change

on:
  push:
    branches:
      - master

jobs:
  detect-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Determine frontend image version
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'docker-qna-frontend/') }}
        id: frontend-version
        run: |
          CURRENT_VERSION=$(grep -oP 'honeykwak/docker-qna-frontend:\K[0-9]+\.[0-9]+' manifest/frontend/4.frontend.yaml)
          if [ -z "$CURRENT_VERSION" ]; then
            CURRENT_VERSION=3.0
          fi
          NEW_VERSION=$(echo $CURRENT_VERSION + 1.0 | bc)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Build and Push Frontend Image
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'docker-qna-frontend/') }}
        run: |
          docker build -t honeykwak/docker-qna-frontend:${{ env.NEW_VERSION }} docker-qna-frontend
          docker push honeykwak/docker-qna-frontend:${{ env.NEW_VERSION }}
      - name: Update frontend.yaml
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'docker-qna-frontend/') }}
        run: |
          sed -i 's|image: honeykwak/docker-qna-frontend:.*|image: honeykwak/docker-qna-frontend:${{ env.NEW_VERSION }}|' manifest/frontend/4.frontend.yaml
      - name: Determine backend image version
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'docker-qna-backend/') }}
        id: backend-version
        run: |
          CURRENT_VERSION=$(grep -oP 'honeykwak/docker-qna-backend:\K[0-9]+\.[0-9]+' manifest/backend/3.backend.yaml)
          if [ -z "$CURRENT_VERSION" ]; then
            CURRENT_VERSION=2.0
          fi
          NEW_VERSION=$(echo $CURRENT_VERSION + 1.0 | bc)
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
      - name: Build and Push Backend Image
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'docker-qna-backend/') }}
        run: |
          docker build -t honeykwak/docker-qna-backend:${{ env.NEW_VERSION }} docker-qna-backend
          docker push honeykwak/docker-qna-backend:${{ env.NEW_VERSION }}
      - name: Update backend.yaml
        if: ${{ steps.changed-files.outputs.all_changed_files != '' && contains(steps.changed-files.outputs.all_changed_files, 'docker-qna-backend/') }}
        run: |
          sed -i 's|image: honeykwak/docker-qna-backend:.*|image: honeykwak/docker-qna-backend:${{ env.NEW_VERSION }}|' manifest/backend/3.backend.yaml
      - name: Commit and push changes
        if: |
          steps.changed-files.outputs.all_changed_files != '' &&
          (contains(steps.changed-files.outputs.all_changed_files, 'docker-qna-frontend/') || 
           contains(steps.changed-files.outputs.all_changed_files, 'docker-qna-backend/'))
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add manifest/frontend/4.frontend.yaml manifest/backend/3.backend.yaml
          git commit -m "Update Docker images in manifest files"
          git push origin master

